version: "3.8"

services:
  mario-kart-ml:
    build: .
    container_name: mario-kart-ml-container
    volumes:
      - .:/app  # Mount the current directory into /app inside the container
    working_dir: /app
    stdin_open: true  # Keep container interactive
    tty: true         # Enable terminal interaction

